replicaCount: 2

image:
  repository: ghcr.io/nikolavrtikola/argo-demo
  tag: "07532602ebfdc3e91a8652f03bb9996754e31d76"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080
  