replicaCount: 2

image:
  repository: ghcr.io/nikolavrtikola/argo-demo
  tag: "d39ef30c7db209cf7e72af84b45d5b375afbd360"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080
  