replicaCount: 2

image:
  repository: ghcr.io/nikolavrtikola/argo-demo
  tag: "213e56f5ad9e3450c4a0cd7dec375fb899e24b8d"
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080
  